# Generated by Django 4.2.14 on 2024-07-22 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_resume', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='name',
            new_name='field_type',
        ),
        migrations.AddField(
            model_name='resume',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='job_title',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField()),
                ('title', models.CharField(max_length=70, null=True)),
                ('company_name', models.CharField(max_length=70, null=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_resume.resume')),
            ],
        ),
    ]
